-- The block is meant to loop and the client can do two sessions on the
-- same calendar day (e.g. complete session 3 in the morning, jump on
-- session 4 in the evening which maps back to week 1 of the loop). The
-- (client, item, session_date, set_number) unique key collided in that
-- case: the second run reused the first run's rows because they share
-- the same date and items.
--
-- Replace the date-based grouping with a session_run_id (one UUID per
-- actual run of a session). session_date stays as a metadata column for
-- display, but it no longer drives uniqueness.

alter table public.workout_logs
  add column if not exists session_run_id uuid;

-- Backfill existing rows with a deterministic UUID per (client, week, date)
-- so every set logged in the same historical session shares one run id.
update public.workout_logs wl
set session_run_id = md5(
  wl.client_id::text || '|' ||
  coalesce(
    (select i.week_id::text from public.program_items i where i.id = wl.program_item_id),
    'orphan'
  ) || '|' ||
  wl.session_date::text
)::uuid
where wl.session_run_id is null;

alter table public.workout_logs
  alter column session_run_id set not null,
  alter column session_run_id set default gen_random_uuid();

-- Drop the old unique constraint (its name is auto-generated by Postgres
-- so look it up dynamically).
do $$
declare
  c_name text;
begin
  select conname into c_name
  from pg_constraint
  where conrelid = 'public.workout_logs'::regclass
    and contype = 'u'
    and conkey @> array[
      (select attnum from pg_attribute where attrelid = 'public.workout_logs'::regclass and attname = 'session_date')
    ];
  if c_name is not null then
    execute format('alter table public.workout_logs drop constraint %I', c_name);
  end if;
end $$;

-- New unique constraint: same item logged in two different runs is allowed,
-- two sets of the same number within the same run is not.
alter table public.workout_logs
  add constraint workout_logs_unique_set
  unique (client_id, program_item_id, session_run_id, set_number);

create index if not exists idx_workout_logs_run
  on public.workout_logs (client_id, session_run_id);
